[package]
name = "street_fighter_back"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
borsh = "1.5.5"
solana-program = "2.2.1"

[lib]
crate-type = ["cdylib", "lib"]
